In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import pickle

%matplotlib inline

from contextlib import contextmanager

@contextmanager
def timer(name):
    start_time = time.time()
    yield
    print(f'[{name} done in {time.time() - start_time:.2f} s]')

In [2]:
assigment = pd.DataFrame()
with timer('read assigment csv'):
    for day in ['25','26','27','28','29','30','31']:
        temp = pd.read_csv("data/train201710"+day+".csv", sep=",")
        temp['O_TIME'] = pd.to_datetime('2017-10-'+day+' '+temp['O_TIME'],format='%Y-%m-%d %H:%M:%S')
        temp = temp.groupby(['O_LINENO', 'O_TERMINALNO']).apply(lambda x:x.sort_values(by='O_TIME', ascending=True))
        assigment = pd.concat([assigment,temp])
assigment['O_DATA'] = assigment['O_TIME'].dt.day

[read assigment csv done in 432.01 s]

In [3]:
assigment.O_LATITUDE.max()

89.7332

In [4]:
np.percentile(assigment.O_LATITUDE,99.99)

40.0725

In [5]:
assigment.O_LATITUDE.max()

89.7332

In [6]:
assigment.O_LONGITUDE.max()

178.282

In [7]:
np.percentile(assigment.O_LONGITUDE,99.9)

117.85499999999999

In [8]:
assigment.head()

                               O_LINENO  O_TERMINALNO              O_TIME  \
O_LINENO O_TERMINALNO
1        901530       2988547         1        901530 2017-10-25 06:00:07
                      2989501         1        901530 2017-10-25 06:00:17
                      2990476         1        901530 2017-10-25 06:00:27
                      2988927         1        901530 2017-10-25 06:00:37
                      2989891         1        901530 2017-10-25 06:00:47

                               O_LONGITUDE  O_LATITUDE  O_SPEED  O_MIDDOOR  \
O_LINENO O_TERMINALNO
1        901530       2988547      117.195     39.1275        0          0
                      2989501      117.195     39.1275        0          0
                      2990476      117.195     39.1275        0          0
                      2988927      117.195     39.1275        0          0
                      2989891      117.195     39.1275        0          0

                               O_REARDOOR  O_FRONTDOOR  O_UP  O_RUN  \
O_LINENO O_TERMINALNO
1        901530       2988547           0            1     1      0
                      2989501           0            1     1      0
                      2990476           0            1     1      0
                      2988927           0            1     1      0
                      2989891           0            1     1      0

                               O_NEXTSTATIONNO  O_DATA
O_LINENO O_TERMINALNO
1        901530       2988547               30      25
                      2989501               30      25
                      2990476               30      25
                      2988927               30      25
                      2989891               30      25

In [2]:
pd.read_csv('toBePredicted_0706_result.csv')

,LINE,TERMINALNO,UP,pred_start_stop_ID,pred_end_stop_ID,realTime,distance,pred1,pred2,Distance,Distance1,div_dist,new_pred
0,678,904388,0,11,12,2017-10-28 14:00:00,0.417984,140.476949,140.476949,0.679068,1.097053,0.618993,86.954293
1,678,904388,0,12,13,2017-10-28 14:00:00,0.000000,158.902420,158.902420,0.744740,0.744740,1.000000,158.902420
2,678,904388,0,13,14,2017-10-28 14:00:00,0.000000,71.855045,71.855045,0.479191,0.479191,1.000000,71.855045
3,678,904388,0,14,15,2017-10-28 14:00:00,0.000000,97.153799,97.153799,0.367919,0.367919,1.000000,97.153799
4,678,904388,0,15,16,2017-10-28 14:00:00,0.000000,243.789968,243.789968,1.141722,1.141722,1.000000,243.789968
5,678,904388,0,16,17,2017-10-28 14:00:00,0.000000,137.804543,137.804543,0.578620,0.578620,1.000000,137.804543
6,678,904388,0,17,18,2017-10-28 14:00:00,0.000000,74.649868,74.649868,0.410412,0.410412,1.000000,74.649868
7,678,904388,0,18,19,2017-10-28 14:00:00,0.000000,118.296734,118.296734,0.665032,0.665032,1.000000,118.296734
8,678,904388,0,19,20,2017-10-28 14:00:00,0.000000,187.131309,187.131309,0.907266,0.907266,1.000000,187.131309
9,678,904388,0,20,21,2017-10-28 14:00:00,0.000000,142.429733,142.429733,0.471062,0.471062,1.000000,142.429733
10,678,904388,0,21,22,2017-10-28 14:00:00,0.000000,145.578509,145.578509,0.421424,0.421424,1.000000,145.578509
11,678,904388,0,22,23,2017-10-28 14:00:00,0.000000,249.026619,249.026619,0.781853,0.781853,1.000000,249.026619
12,678,904388,0,23,24,2017-10-28 14:00:00,0.000000,162.394970,162.394970,0.536211,0.536211,1.000000,162.394970
13,678,904388,0,24,25,2017-10-28 14:00:00,0.000000,302.152028,302.152028,0.940935,0.940935,1.000000,302.152028
14,678,904388,0,25,26,2017-10-28 14:00:00,0.000000,69.767060,69.767060,0.329857,0.329857,1.000000,69.767060
15,678,904388,0,26,27,2017-10-28 14:00:00,0.000000,236.417951,236.417951,0.832697,0.832697,1.000000,236.417951
16,678,904388,0,27,28,2017-10-28 14:00:00,0.000000,89.716063,89.716063,0.568030,0.568030,1.000000,89.716063
17,678,904388,0,28,29,2017-10-28 14:00:00,0.000000,98.331274,98.331274,0.554299,0.554299,1.000000,98.331274
18,678,904388,0,29,30,2017-10-28 14:00:00,0.000000,198.551431,198.551431,0.777112,0.777112,1.000000,198.551431
19,678,904388,0,30,31,2017-10-28 14:00:00,0.000000,288.137994,288.137994,1.270259,1.270259,1.000000,288.137994
20,678,904388,0,31,32,2017-10-28 14:00:00,0.000000,75.151900,75.151900,0.465693,0.465693,1.000000,75.151900
21,678,904388,0,32,33,2017-10-28 14:00:00,0.000000,135.422125,135.422125,0.737378,0.737378,1.000000,135.422125
22,13,902540,1,6,7,2017-10-26 17:00:00,0.203901,101.331333,101.331333,0.222678,0.426580,0.522009,52.895844
23,13,902540,1,7,8,2017-10-26 17:00:00,0.000000,80.779494,80.779494,0.360476,0.360476,1.000000,80.779494
24,13,902540,1,8,9,2017-10-26 17:00:00,0.000000,203.354850,203.354850,0.617953,0.617953,1.000000,203.354850
25,13,902540,1,9,10,2017-10-26 17:00:00,0.000000,84.590059,84.590059,0.406106,0.406106,1.000000,84.590059
26,13,902540,1,10,11,2017-10-26 17:00:00,0.000000,153.454493,153.454493,0.597665,0.597665,1.000000,153.454493
27,13,902540,1,11,12,2017-10-26 17:00:00,0.000000,309.523615,309.523615,0.940889,0.940889,1.000000,309.523615
28,13,902540,1,12,13,2017-10-26 17:00:00,0.000000,139.624037,139.624037,0.545657,0.545657,1.000000,139.624037
29,13,902540,1,13,14,2017-10-26 17:00:00,0.000000,91.816133,91.816133,0.289686,0.289686,1.000000,91.816133
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490350,866,905573,1,17,18,2017-10-30 08:00:00,0.000000,117.856281,117.856281,0.494170,0.494170,1.000000,117.856281
490351,866,905573,1,18,19,2017-10-30 08:00:00,0.000000,179.132671,179.132671,0.622826,0.622826,1.000000,179.132671
490352,866,905573,1,19,20,2017-10-30 08:00:00,0.000000,226.638833,226.638833,0.759175,0.759175,1.000000,226.638833
490353,866,905581,1,9,10,2017-10-30 20:00:00,0.369525,153.752419,153.752419,0.209717,0.579242,0.362055,55.666770
490354,866,905581,1,10,11,2017-10-30 20:00:00,0.000000,153.979978,153.979978,0.774276,0.774276,1.000000,153.979978
490355,866,905581,1,11,12,2017-10-30 20:00:00,0.000000,110.214684,110.214684,0.603496,0.603496,1.000000,110.214684
490356,866,905581,1,12,13,2017-10-30 20:00:00,0.000000,119.663522,119.663522,0.620998,0.620998,1.000000,119.663522
490357,866,905581,1,13,14,2017-10-30 20:00:00,0.000000,118.398104,118.398104,0.675103,0.675103,1.000000,118.398104
490358,866,905581,1,14,15,2017-10-30 20:00:00,0.000000,293.429042,293.429042,2.309480,2.309480,1.000000,293.429042
490359,866,905581,1,15,16,2017-10-30 20:00:00,0.000000,287.541162,287.541162,1.589164,1.589164,1.000000,287.541162
490360,866,905581,1,16,17,2017-10-30 20:00:00,0.000000,128.218229,128.218229,0.615316,0.615316,1.000000,128.218229
490361,866,905581,1,17,18,2017-10-30 20:00:00,0.000000,104.527196,104.527196,0.494170,0.494170,1.000000,104.527196
490362,866,905581,1,18,19,2017-10-30 20:00:00,0.000000,121.556894,121.556894,0.622826,0.622826,1.000000,121.556894
490363,866,905581,1,19,20,2017-10-30 20:00:00,0.000000,145.526185,145.526185,0.759175,0.759175,1.000000,145.526185
490364,866,905581,1,20,21,2017-10-30 20:00:00,0.000000,179.108748,179.108748,0.909008,0.909008,1.000000,179.108748
490365,866,905581,1,21,22,2017-10-30 20:00:00,0.000000,119.806628,119.806628,0.356678,0.356678,1.000000,119.806628
490366,866,905581,1,22,23,2017-10-30 20:00:00,0.000000,312.908075,312.908075,1.490576,1.490576,1.000000,312.908075
490367,866,905581,1,23,24,2017-10-30 20:00:00,0.000000,118.295186,118.295186,0.611604,0.611604,1.000000,118.295186
490368,866,905581,1,24,25,2017-10-30 20:00:00,0.000000,151.281779,151.281779,1.062054,1.062054,1.000000,151.281779
490369,866,905581,1,25,26,2017-10-30 20:00:00,0.000000,56.988362,56.988362,0.417752,0.417752,1.000000,56.988362
490370,866,905581,1,26,27,2017-10-30 20:00:00,0.000000,91.544301,91.544301,0.661101,0.661101,1.000000,91.544301
490371,866,905581,1,27,28,2017-10-30 20:00:00,0.000000,110.461420,110.461420,0.665175,0.665175,1.000000,110.461420
490372,866,905581,1,28,29,2017-10-30 20:00:00,0.000000,95.177234,95.177234,0.499083,0.499083,1.000000,95.177234
490373,866,905581,1,29,30,2017-10-30 20:00:00,0.000000,73.946541,73.946541,0.464358,0.464358,1.000000,73.946541
490374,866,905581,1,30,31,2017-10-30 20:00:00,0.000000,89.045463,89.045463,0.588394,0.588394,1.000000,89.045463
490375,866,905581,1,31,32,2017-10-30 20:00:00,0.000000,69.299618,69.299618,0.399832,0.399832,1.000000,69.299618
490376,866,905581,1,32,33,2017-10-30 20:00:00,0.000000,61.053421,61.053421,0.400796,0.400796,1.000000,61.053421
490377,866,905581,1,33,34,2017-10-30 20:00:00,0.000000,68.724148,68.724148,0.352615,0.352615,1.000000,68.724148
490378,866,905581,1,34,35,2017-10-30 20:00:00,0.000000,226.725367,226.725367,1.965153,1.965153,1.000000,226.725367
490379,866,905581,1,35,36,2017-10-30 20:00:00,0.000000,45.435209,45.435209,0.334302,0.334302,1.000000,45.435209